<Program> ::= <Initialize> <Hadamard> <OracleBlock> <FinalHadamard> <Measure>

<Initialize> ::= 
    "qc = QuantumCircuit(2, 2)\n"
    "qc.x(1)\n"

<Hadamard> ::= 
    "qc.h(0)\n"
    "qc.h(1)\n"

<OracleBlock> ::= 
    "## Oracle start\n"
    <OracleGateList>
    "## Oracle end\n"

<OracleGateList> ::= 
    <OracleGate>
  | <OracleGate> <OracleGateList>

<OracleGate> ::= 
    <SingleQubitGate>
  | <TwoQubitGate>

<SingleQubitGate> ::= 
    "qc.x(" <Qubit> ")\n"
  | "qc.z(" <Qubit> ")\n"
  | "qc.s(" <Qubit> ")\n"
  | "qc.sdg(" <Qubit> ")\n"
  | "qc.t(" <Qubit> ")\n"
  | "qc.tdg(" <Qubit> ")\n"
  | "qc.h(" <Qubit> ")\n"

<TwoQubitGate> ::= 
    "qc.cx(" <QubitPair> ")\n"
  | "qc.cz(" <QubitPair> ")\n"

<FinalHadamard> ::= 
    "qc.h(0)\n"

<Measure> ::= 
    "qc.measure(0,0)\n"
    "qc.measure(1, 1)\n"

<Qubit> ::= "0" | "1"

<QubitPair> ::= "0,1" | "1,0"