<Program> ::=
    <Initialize>
    <InitialSetupSequence>
    <OptionalBarrier>
    <OraclePlaceholder>
    <OptionalBarrier>
    <FinalSetupSequence>
    <Measure>

<Initialize> ::=
    "qc = QuantumCircuit(2, 1)\n"

<InitialSetupSequence> ::= <InitialSetupStep1> <InitialSetupStep2> <InitialSetupStep3>
<InitialSetupStep1> ::= "qc.x(1)\n" | <SingleQubitGateOnAncilla>
<InitialSetupStep2> ::= "qc.h(1)\n" | <SingleQubitGateOnAncilla>
<InitialSetupStep3> ::= "qc.h(0)\n" | <SingleQubitGateOnInput>

<FinalSetupSequence> ::= <FinalSetupStep>
<FinalSetupStep> ::= "qc.h(0)\n" | <SingleQubitGateOnInput>

<Measure> ::=
    "qc.measure(0, 0)\n"

<OraclePlaceholder> ::=
    "# ORACLE_INSERTION_POINT\n"

<OptionalBarrier> ::=
      ""
    | "qc.barrier()\n"

<SingleQubitGateOnInput> ::=
    "qc.x(0)\n"
  | "qc.h(0)\n"
  | "qc.s(0)\n"
  | "qc.sxdg(0)\n"
  | "qc.t(0)\n"
  | "qc.tdg(0)\n"
  | "qc.rx(pi/2, 0)\n"
  | "qc.ry(pi/4, 0)\n"
  | "qc.p(pi/4, 0)\n"
  | "qc.u1(pi/3, 0)\n"

<SingleQubitGateOnAncilla> ::=
    "qc.x(1)\n"
  | "qc.h(1)\n"
  | "qc.s(1)\n"
  | "qc.sxdg(1)\n"
  | "qc.t(1)\n"
  | "qc.tdg(1)\n"
  | "qc.rx(pi/2, 1)\n"
  | "qc.ry(pi/4, 1)\n"
  | "qc.p(pi/4, 1)\n"
  | "qc.u1(pi/3, 1)\n"
